services:
  pets:
    image: petstorepetservice:latest
    volumes:
      - pet_pets:/var/lib/pet_pets
    restart: always
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
    ports:
      - 8081:8081
    networks:
      network:
        ipv4_address: 10.5.0.10      
  orders:
    image: petstoreorderservice:latest
    volumes:
      - pet_orders:/var/lib/pet_orders
    restart: always
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
    ports:
      - 8083:8083
    networks:
      network:
        ipv4_address: 10.5.0.30
  products:
    image: petstoreproductservice:latest
    volumes:
      - pet_products:/var/lib/pet_products
    restart: always
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082      
    ports:
      - 8082:8082
    networks:
      network:
        ipv4_address: 10.5.0.20
  ui:
    image: petstoreapp:latest
    volumes:
      - pet_ui:/var/lib/pet_ui
    ports:
      - 8080:8080
    restart: always
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://10.5.0.10:8081
      - PETSTOREPRODUCTSERVICE_URL=http://10.5.0.20:8082
      - PETSTOREORDERSERVICE_URL=http://10.5.0.30:8083
    networks:
      network:
        ipv4_address: 10.5.0.80
volumes:
  pet_ui:
  pet_orders:
  pet_products:
  pet_pets:
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1