services:
  pets:
    image: petstorepetservice:latest
    volumes:
      - pet_pets:/var/lib/pet_pets
    restart: always
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
      - DATA_SOURCE_CONNECTION_STRING=jdbc:postgresql://10.5.0.5:5432/postgres
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASSWORD=example
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      network:
        ipv4_address: 10.5.0.10      
  orders:
    image: petstoreorderservice:latest
    volumes:
      - pet_orders:/var/lib/pet_orders
    restart: always
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
      - RESERVATIONS_URL=https://ordersreservation-20230820115219084.azurewebsites.net
    ports:
      - 8083:8083
    networks:
      network:
        ipv4_address: 10.5.0.30
  products:
    image: petstoreproductservice:latest
    volumes:
      - pet_products:/var/lib/pet_products
    restart: always
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082
      - DATA_SOURCE_CONNECTION_STRING=jdbc:postgresql://10.5.0.5:5432/postgres
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASSWORD=example
    ports:
      - 8082:8082
    depends_on:
      - db
    networks:
      network:
        ipv4_address: 10.5.0.20
  ui:
    image: petstoreapp:latest
    volumes:
      - pet_ui:/var/lib/pet_ui
    ports:
      - 8080:8080
    restart: always
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://10.5.0.10:8081
      - PETSTOREPRODUCTSERVICE_URL=http://10.5.0.20:8082
      - PETSTOREORDERSERVICE_URL=http://10.5.0.30:8083
    networks:
      network:
        ipv4_address: 10.5.0.80
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      network:
        ipv4_address: 10.5.0.5
volumes:
  pet_ui:
  pet_orders:
  pet_products:
  pet_pets:
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1